# Generated by Django 4.1 on 2022-08-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_valeitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='almacen',
            field=models.CharField(max_length=30, unique=True, verbose_name='almacen'),
        ),
    ]
