# Generated by Django 4.1 on 2022-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_alter_almacen_almacen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificaciones',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='bultos',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='casilla',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='conduce',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='conocimiento',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='expedicion',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='manifiesto',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='scompra',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='tbultos',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='tchapa',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='tci',
        ),
        migrations.RemoveField(
            model_name='recepcion',
            name='transportista',
        ),
        migrations.AddField(
            model_name='mercancia',
            name='precio',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
